{
 "title": "Fn usage",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(fn_queued)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(fn_running)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(fn_completed)" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(fn_failed) + sum(fn_timeouts) + sum(fn_server_busy)"
    }
   ]
  },
  {
   "title": "Total queued",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(fn_queued)", "legendFormat": "Total queued" }
   ]
  },
  {
   "title": "Total running",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(fn_running)", "legendFormat": "Total running" }
   ]
  },
  {
   "title": "Total completed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(fn_completed)", "legendFormat": "Total completed" }
   ]
  },
  {
   "title": "Total incomplete",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(fn_failed)", "legendFormat": "Total failed" },
    { "expr": "sum(fn_timeouts)", "legendFormat": "Total timeouts" },
    { "expr": "sum(fn_server_busy)", "legendFormat": "Total server too busy" }
   ]
  },
  {
   "title": "Queued",
   "type": "graph",
   "description": "Queued tasks, per function path",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fn_queued", "legendFormat": "{{fn_appname}} {{fn_path}}" }
   ]
  },
  {
   "title": "Running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fn_running", "legendFormat": "{{fn_appname}} {{fn_path}}" }
   ]
  },
  {
   "title": "Completed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "fn_completed", "legendFormat": "{{fn_appname}} {{fn_path}}" }
   ]
  },
  {
   "title": "Incomplete",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fn_failed",
     "legendFormat": "{{fn_appname}} {{fn_path}} failed"
    },
    {
     "expr": "fn_timeouts",
     "legendFormat": "{{fn_appname}} {{fn_path}} timeouts"
    },
    {
     "expr": "fn_server_busy",
     "legendFormat": "{{fn_appname}} {{fn_path}} server busy"
    }
   ]
  }
 ]
}