{
 "title": "Spark Overview",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster",
    "query": "label_values(jvm_memory_init{job=\"banzaicloud-pushgateway\"},cluster_name)"
   },
   {
    "name": "pod_ip",
    "label": "Pod ip",
    "query": "label_values(jvm_memory_init{cluster_name=\"$cluster_name\",job=\"banzaicloud-pushgateway\"}, instance)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(kube_pod_info{cluster_name=\"$cluster_name\", component=\"kube-state-metrics\",pod_ip=\"$pod_ip\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU System Load(1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable{instance=~\"$host\", cluster_name=\"$cluster_name\"} * 100) / node_memory_MemTotal{instance=~\"$host\", cluster_name=\"$cluster_name\"})",
     "legendFormat": "{{ }}"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (java_lang_operatingsystem_freeswapspacesize{instance=~\"$instance\"} / on(instance) java_lang_operatingsystem_totalswapspacesize{instance=~\"$instance\"} * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load(5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(node_cpu{instance=~\"$host\"}) by (cpu))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (irate(node_cpu{cluster_name=\"$cluster_name\",instance=\"$host\",mode=\"system\"}[5m])) ) / scalar(count(count by (cpu)(node_cpu{instance=\"$host\"})))",
     "legendFormat": "system"
    },
    {
     "expr": "(sum by (instance) (irate(node_cpu{cluster_name=\"$cluster_name\",instance=\"$host\",mode=\"user\"}[5m])) ) / scalar(count(count by (cpu)(node_cpu{instance=\"$host\"})))",
     "legendFormat": "user"
    },
    {
     "expr": "(sum by (instance) (irate(node_cpu{cluster_name=\"$cluster_name\",instance=\"$host\",mode=\"idle\"}[5m])) ) / scalar(count(count by (cpu)(node_cpu{instance=\"$host\"})))",
     "legendFormat": "idle"
    },
    {
     "expr": "(sum by (instance) (irate(node_cpu{cluster_name=\"$cluster_name\",instance=\"$host\",mode=\"softirq\"}[5m])) ) / scalar(count(count by (cpu)(node_cpu{instance=\"$host\"})))",
     "legendFormat": "softirq"
    },
    {
     "expr": "(sum by (instance) (irate(node_cpu{cluster_name=\"$cluster_name\",instance=\"$host\",mode=\"irq\"}[5m])) ) / scalar(count(count by (cpu)(node_cpu{instance=\"$host\"})))",
     "legendFormat": "irq"
    },
    {
     "expr": "(sum by (instance) (irate(node_cpu{cluster_name=\"$cluster_name\",instance=\"$host\",mode=\"iowait\"}[5m])) ) / scalar(count(count by (cpu)(node_cpu{instance=\"$host\"})))",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Memory Heap /NonHeap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used{instance=\"$pod_ip\", type=\"non_heap\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "jvm_memory_used{instance=\"$pod_ip\", type=\"heap\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools_used_bytes{instance=~\"$pod_ip\", cluster_name=\"$cluster_name\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pool}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_memory_gc_time{instance=~\"$pod_ip\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_gc_count{instance=~\"$pod_ip\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instance\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "descriptors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Catalina Request Processor bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "catalina_globalrequestprocessor_bytesreceived{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}} recv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "catalina_globalrequestprocessor_bytessent{instance=~\"$instance\"}",
     "legendFormat": "{{name}} sent"
    }
   ]
  },
  {
   "title": "Catalina Request Processor requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "catalina_globalrequestprocessor_requestcount{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}} count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "catalina_globalrequestprocessor_errorcount{instance=~\"$instance\"}",
     "legendFormat": "{{name}} error"
    }
   ]
  },
  {
   "title": "Catalina Request Processing Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "catalina_globalrequestprocessor_processingtime{instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}